export enum PokemonType{
    NORMAL="NORMAL",
FIRE="FIRE",
WATER="WATER",
ELECTRIC="ELECTRIC",
GRASS="GRASS",
ICE="ICE",
FIGHTING="FIGHTING",
POISON="POISON",
GROUND="GROUND",
FLYING="FLYING",
PSYCHIC="PSYCHIC",
BUG="BUG",
ROCK="ROCK",
GHOST="GHOST",
DRAGON="DRAGON"
}